// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkdNNgYSzFhzaIshp4Eards12hgbXGIY',
    appId: '1:17870675528:web:cb1a3083ff1114813fc27d',
    messagingSenderId: '17870675528',
    projectId: 'push-notifications-test-3efc3',
    authDomain: 'push-notifications-test-3efc3.firebaseapp.com',
    storageBucket: 'push-notifications-test-3efc3.appspot.com',
    measurementId: 'G-LYHYV1SFPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQck7NRC3prt9Vr58aBMoq2v5YeAMOBc',
    appId: '1:17870675528:android:1630a345d96af9d93fc27d',
    messagingSenderId: '17870675528',
    projectId: 'push-notifications-test-3efc3',
    storageBucket: 'push-notifications-test-3efc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnyD_jG8mqVnYDQ8sJ6UCLoMOFt2QSKc',
    appId: '1:17870675528:ios:9296fe20a0fe8ef13fc27d',
    messagingSenderId: '17870675528',
    projectId: 'push-notifications-test-3efc3',
    storageBucket: 'push-notifications-test-3efc3.appspot.com',
    iosBundleId: 'com.jukysuk.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEnyD_jG8mqVnYDQ8sJ6UCLoMOFt2QSKc',
    appId: '1:17870675528:ios:9296fe20a0fe8ef13fc27d',
    messagingSenderId: '17870675528',
    projectId: 'push-notifications-test-3efc3',
    storageBucket: 'push-notifications-test-3efc3.appspot.com',
    iosBundleId: 'com.jukysuk.flutterPushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkdNNgYSzFhzaIshp4Eards12hgbXGIY',
    appId: '1:17870675528:web:f47da3c1a57dafc93fc27d',
    messagingSenderId: '17870675528',
    projectId: 'push-notifications-test-3efc3',
    authDomain: 'push-notifications-test-3efc3.firebaseapp.com',
    storageBucket: 'push-notifications-test-3efc3.appspot.com',
    measurementId: 'G-RYFW7C98NN',
  );
}
